### ISSUE TITLE
Document field

### ISSUE THREAD

**Issue by gileCAD** [ActivistInvestor/AcMgdUtility#1]
What about adding a protected Document field which could be used in the Initialze method of derived classes?

`protected Autodesk.AutoCAD.ApplicationServices.Document doc;

void OnIdle(object sender, EventArgs e)
{
    doc = Application.DocumentManager.MdiActiveDocument;
    if (doc != null)
    {
        Application.Idle -= OnIdle;
        try
        {
            Initialize();
        }
        catch (System.Exception ex)
        {
            doc.Editor.WriteMessage(ex.Message);
        }
    }
}`

**Comment by ActivistInvestor** [comment]
Hi Gile. Thanks for your suggestion.

Since I am treating this as an open collaboration, feel free to make whatever changes you want to contribute to the project. I will add you as a contributor as soon as I figure out how to do that.

________________________________
From: Gilles Chanteau ***@***.***>
Sent: Saturday, March 30, 2024 1:27:05 PM
To: ActivistInvestor/AcMgdUtility ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ActivistInvestor/AcMgdUtility] Document field (Issue #1)


What about adding a protected Document field which could be used in derived classes?
protected Autodesk.AutoCAD.ApplicationServices.Document doc; void OnIdle(object sender, EventArgs e) { doc = Application.DocumentManager.MdiActiveDocument; if (doc != null) { Application.Idle -= OnIdle; try { Initialize(); } catch (System.Exception ex) { doc.Editor.WriteMessage(ex.Message); } } }

**Comment by gileCAD** [comment]
Thanks Tony,

I'm proud to be invited to collaborate with 'The Master'. I learn so much from your contributions.

I'd try to contribute. I'm not that comfortable with GitHub (and English).
